# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Nina Tubau Ribera
title: Computer Scientist (Image processing)
email: tubau.n@wehi.edu.au
website: www.github.com/ninatubau

# Social links
twitter_username: NTubau
github_username:  ninatubau
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: ninitbr
linkedin_username: nina-tubau-ribera-aa248112b 
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profilePic.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nina and I'm a computer science student. With communication and organisational skills, I am looking for a full time job in Medical Imaging starting in October 2019.


  I am most interested in: <mark>Imaging</mark> and <mark>Deep learning</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computer science some of my other interests and hobbies are:
   - Skiing
   - Swimming
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
